- name: Bootstrap dev environment
  hosts: localhost
  connection: local
  roles:
    - role: core
      tags:
        - core
    - role: git
      tags:
        - git
    - role: dotfiles
      tags:
        - dotfiles
