- name: Bootstrap dev environment
  hosts: localhost
  connection: local
  roles:
    - role: core
      tags:
        - core-role
        - dotfiles
    - role: git
      tags:
        - git-role
        - git
    - role: dotfiles
      tags:
        - dotfiles-role
        - dotfiles
