- name: Checkout dotfiles
  git:
    repo: git@github.com-t1dev:0xb7a7dd61/dotfiles.git
    dest: "{{ dev_dir }}/{{ dev_personal_subdir }}/dotfiles"
- name: run init target
  make:
    chdir: "{{ dev_dir }}/{{ dev_personal_subdir }}/dotfiles"
    target: setup
