- name: Ensure .ssh directory exists.
  file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory
- name: Install t1dev github ssh key
  copy:
    src: "{{ playbook_dir }}/.ssh/id_rsa_0xb7a7dd61"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_0xb7a7dd61"
    mode: 0600
- name: Install treasure github ssh key
  copy:
    src: "{{ playbook_dir }}/.ssh/id_rsa_treasure-t1dev"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_treasure-t1dev"
    mode: 0600
- name: Install [[redacted1]] github ssh key
  copy:
    src: "{{ playbook_dir }}/.ssh/id_rsa_redacted1"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_redacted1"
    mode: 0600
- name: Install [[redacted2]] github ssh key
  copy:
    src: "{{ playbook_dir }}/.ssh/id_rsa_redacted2"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa_redacted2"
    mode: 0600
- name: Set .ssh/config github entries
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.ssh/config"
    block: |
      # Treasure account
      Host github.com-treasure
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_rsa_treasure-t1dev
        IdentitiesOnly yes

      # 0xb7a7dd61 account
      Host github.com-t1dev
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_rsa_0xb7a7dd61
        IdentitiesOnly yes

      # redacted1 account
      Host github.com-r1
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_rsa_redacted1
        IdentitiesOnly yes

      # redacted2 account
      Host github.com-r2
        HostName github.com
        User git
        IdentityFile ~/.ssh/id_rsa_redacted2
        IdentitiesOnly yes
